name: Salesforce Code Analyzer

on:
  pull_request:
    branches:
      - BRInt

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      - name: Install Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner

      - name: Run Code Analysis with Severity Threshold
        run: |
          echo "Running static analysis on force-app directory..."
          # This will exit with non-zero status if any issues at or above severity 3 are found
          sf scanner:run --target "force-app" --format table --category "Security" --severity-threshold 3
